### ISSUE TITLE
Freezing problems with SXOS 2.9, when updating to FW 9.0

### ISSUE THREAD

**Issue by vris2809** [rajkosto/ChoiDujour#17]
Hallo,
 Programm stops/Freezing by "Testing for BIS protection 1/6"

**Comment by RandLoki** [comment]
I am having the same exact issue. Please help :)

**Comment by vris2809** [comment]
Ok, is a SXOS 2.9 problem, with SXOS 2.9.1 ChoiDujour is working fine
